// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnBhASQQrJXco8QW5C2FMw3QookLHyle8',
    appId: '1:26869223573:web:823cbd558b99266f138b9c',
    messagingSenderId: '26869223573',
    projectId: 'uffluir-8968e',
    authDomain: 'uffluir-8968e.firebaseapp.com',
    storageBucket: 'uffluir-8968e.appspot.com',
    measurementId: 'G-MWBDDS536C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMgnys4CnzvYhn7QFOD9M0y2MuPMc-dSo',
    appId: '1:26869223573:android:4a1af23b38bbd2f6138b9c',
    messagingSenderId: '26869223573',
    projectId: 'uffluir-8968e',
    storageBucket: 'uffluir-8968e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARx5gmkyl8Hp_SrxmEhYw8_olwmFWJ5KU',
    appId: '1:26869223573:ios:0afa7d2165c624fa138b9c',
    messagingSenderId: '26869223573',
    projectId: 'uffluir-8968e',
    storageBucket: 'uffluir-8968e.appspot.com',
    androidClientId: '26869223573-5pv9e4obotlc0doaj9epg93no4gau5of.apps.googleusercontent.com',
    iosClientId: '26869223573-7praq6cf69i0tgpa15rid8t7kjb65b0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.uffluir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARx5gmkyl8Hp_SrxmEhYw8_olwmFWJ5KU',
    appId: '1:26869223573:ios:0afa7d2165c624fa138b9c',
    messagingSenderId: '26869223573',
    projectId: 'uffluir-8968e',
    storageBucket: 'uffluir-8968e.appspot.com',
    androidClientId: '26869223573-5pv9e4obotlc0doaj9epg93no4gau5of.apps.googleusercontent.com',
    iosClientId: '26869223573-7praq6cf69i0tgpa15rid8t7kjb65b0e.apps.googleusercontent.com',
    iosBundleId: 'com.example.uffluir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnBhASQQrJXco8QW5C2FMw3QookLHyle8',
    appId: '1:26869223573:web:67eeefd698a4d136138b9c',
    messagingSenderId: '26869223573',
    projectId: 'uffluir-8968e',
    authDomain: 'uffluir-8968e.firebaseapp.com',
    storageBucket: 'uffluir-8968e.appspot.com',
    measurementId: 'G-M9J78HFWB3',
  );

}